
title: Living Materials Atlas
description: A public-facing atlas of protocols, materials, tools, curiosities, and outcomes for engineered living materials.
theme: minima
baseurl: ""
url: ""

collections:
  protocols:
    output: true
    permalink: /protocols/:slug/
  materials:
    output: true
    permalink: /materials/:slug/
  tools:
    output: true
    permalink: /tools/:slug/
  atlas:
    output: true
    permalink: /atlas/:slug/
  curiosities:
    output: true
    permalink: /curiosities/:slug/

defaults:
  - scope: {path: "", type: "protocols"}
    values: {layout: entry, section: protocols}
  - scope: {path: "", type: "materials"}
    values: {layout: entry, section: materials}
  - scope: {path: "", type: "tools"}
    values: {layout: entry, section: tools}
  - scope: {path: "", type: "atlas"}
    values: {layout: entry, section: atlas}
  - scope: {path: "", type: "curiosities"}
    values: {layout: entry, section: curiosities}
